// 定义服务大厅接口数据
import type { hotelApp } from '../types/hotel'
import { ref } from 'vue'
export const hotelData = ref<hotelApp[]>([{
    src: 'http://cloud.zhgn.cn:808/phone/hotel/meeting.png',
    url: '/subpackages/hotel/applyUnion',
    content: '申请入会',
    id: 1,
    mine: true
}, {
    src: 'http://cloud.zhgn.cn:808/phone/hotel/KPI.png',
    url: '/subpackages/hotel/membershipReview',
    content: '入会审核',
    id: 2,
    mine: true
}, {
    src: 'http://cloud.zhgn.cn:808/phone/hotel/xuexi.png',
    url: '/subpackages/hotel/detail',
    content: '我要学习',
    id: 3,
    mine: true
}, {
    src: 'http://cloud.zhgn.cn:808/phone/hotel/exam.png',
    url: '/subpackages/hotel/detail',
    content: '我要考试',
    id: 4,
    mine: false
}, {
    src: 'http://cloud.zhgn.cn:808/phone/hotel/fuxi.png',
    url: '/subpackages/hotel/detail',
    content: '我要复习',
    id: 5,
    mine: true
}, {
    src: 'http://cloud.zhgn.cn:808/phone/hotel/meeting.png',
    url: '/subpackages/hotel/detail',
    content: '测试内容6',
    id: 6,
    mine: false
}, {
    src: 'http://cloud.zhgn.cn:808/phone/hotel/KPI.png',
    url: '/subpackages/hotel/detail',
    content: '测试内容7',
    id: 7,
    mine: true
}, {
    src: 'http://cloud.zhgn.cn:808/phone/hotel/xuexi.png',
    url: '/subpackages/hotel/detail',
    content: '测试内容8',
    id: 8,
    mine: false
}, {
    src: 'http://cloud.zhgn.cn:808/phone/hotel/exam.png',
    url: '/subpackages/hotel/detail',
    content: '测试内容9',
    id: 9,
    mine: true
}, {
    src: 'http://cloud.zhgn.cn:808/phone/hotel/fuxi.png',
    url: '/subpackages/hotel/detail',
    content: '测试内容0',
    id: 10,
    mine: false
}])